name = "clicky-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ELEVENLABS_VOICE_ID = "kPzsL2i3teMYv0FxEYQ6"
FISH_AUDIO_PRIMARY_REFERENCE_ID = "b19f2b60836049a296547c965a0a3b79"
FISH_AUDIO_SECONDARY_REFERENCE_ID = "6b95e07214b745f68086b82f1a817315"
